### ISSUE TITLE
Missing function named AutoRegression in module distributions

### ISSUE THREAD

**Issue by lishen** [mattjj/pyhsmm-autoregressive#7]
I'm having the following error when running the demo.py script:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-beb7d77467a8> in <module>()
      9 truemodel = m.ARHSMM(
     10         alpha=4.,init_state_concentration=4.,
---> 11         obs_distns=[d.AutoRegression(A=A,sigma=np.eye(2)) for A in As],
     12         dur_distns=[pyhsmm.basic.distributions.PoissonDuration(alpha_0=4*25,beta_0=4)
     13             for state in range(len(As))],

AttributeError: 'module' object has no attribute 'AutoRegression'

**Comment by mattjj** [comment]
What's your version of pybasicbayes? I recently updated this code so that it only works with the github version of pybasicbayes (not the pypi version installed via pip). I haven't updated the pypi version yet, though I can soon.

Try installing a more updated pybasicbayes this way:

```
git clone --recursive https://github.com/mattjj/pybasicbayes.git
cd pybasicbayes
pip install -e .
```

Let me know if you still see a problem with the updated pybasicbayes.

**Comment by lishen** [comment]
The problem was solved after upgrading the pybasicbayes module.

**Comment by mattjj** [comment]
Cool, just updated the pypi versions of pybasicbayes and pyhsmm-autoregressive so that the pip install should work.
